// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://bsmclnbeywqosuhijhae.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJzbWNsbmJleXdxb3N1aGlqaGFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwNzEzNTEsImV4cCI6MjA3NDY0NzM1MX0.zISz01Dxi46WtrdOKwFcxxHy7ypLJeD95HH4gDW4Ob8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);